language: bash
services: docker

env:
  - VERSION=7.2-rc VARIANT=
  - VERSION=7.2-rc VARIANT=alpine
  - VERSION=7.2-rc VARIANT=apache
  - VERSION=7.2-rc VARIANT=fpm
  - VERSION=7.2-rc VARIANT=fpm/alpine
  - VERSION=7.2-rc VARIANT=zts
  - VERSION=7.2-rc VARIANT=zts/alpine
  - VERSION=7.1 VARIANT=
  - VERSION=7.1 VARIANT=alpine
  - VERSION=7.1 VARIANT=apache
  - VERSION=7.1 VARIANT=fpm
  - VERSION=7.1 VARIANT=fpm/alpine
  - VERSION=7.1 VARIANT=zts
  - VERSION=7.1 VARIANT=zts/alpine
  - VERSION=7.0 VARIANT=
  - VERSION=7.0 VARIANT=alpine
  - VERSION=7.0 VARIANT=apache
  - VERSION=7.0 VARIANT=fpm
  - VERSION=7.0 VARIANT=fpm/alpine
  - VERSION=7.0 VARIANT=zts
  - VERSION=7.0 VARIANT=zts/alpine
  - VERSION=5.6 VARIANT=
  - VERSION=5.6 VARIANT=alpine
  - VERSION=5.6 VARIANT=apache
  - VERSION=5.6 VARIANT=fpm
  - VERSION=5.6 VARIANT=fpm/alpine
  - VERSION=5.6 VARIANT=zts
  - VERSION=5.6 VARIANT=zts/alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="php:${VERSION}${VARIANT:+-$VARIANT}"
  - image="${image//'/'/-}"

script:
  - travis_retry docker build -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
