language: bash

# for secret experimental features ;)
dist: trusty

env:
  - VERSION=5.6 VARIANT=
  - VERSION=5.6 VARIANT=apache
  - VERSION=5.6 VARIANT=fpm
  - VERSION=5.5 VARIANT=
  - VERSION=5.5 VARIANT=apache
  - VERSION=5.5 VARIANT=fpm
  - VERSION=5.4 VARIANT=
  - VERSION=5.4 VARIANT=apache
  - VERSION=5.4 VARIANT=fpm

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="php:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - docker build -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"

# vim:set et ts=2 sw=2:
